import product1 from "../assets/Images/food1.jpg";
import product2 from "../assets/Images/food2.jpg";
import product3 from "../assets/Images/food3.webp";
import product4 from "../assets/Images/food4.jpg";
import product5 from "../assets/Images/access1.jpg";
import product6 from "../assets/Images/toy1.webp";
import product7 from "../assets/Images/access2.jpg";
import product8 from "../assets/Images/groom1.jpg";
import product9 from "../assets/Images/access3.jpg";
import product10 from "../assets/Images/access4.jpg";
import product11 from "../assets/Images/supply1.webp";
import product12 from "../assets/Images/treat1.jpg";
import product13 from "../assets/Images/food5.jpg";
import product14 from "../assets/Images/food6.jpg";
import product15 from "../assets/Images/food7.jpg";
import product16 from "../assets/Images/food8.webp";
import product17 from '../assets/Images/food9.jpg';
import product18 from '../assets/Images/food10.jpg';
import product19 from '../assets/Images/food11.jpg';
import product20 from '../assets/Images/food12.webp';
import product21 from '../assets/Images/food13.jpg';
import product22 from '../assets/Images/food14.webp';
import product23 from '../assets/Images/food15.webp';
import product24 from '../assets/Images/food16.webp';
import product25 from '../assets/Images/groom2.webp';
import product26 from '../assets/Images/toy2.webp';
import product27 from '../assets/Images/supply2.webp';
import product28 from '../assets/Images/treat2.jpg';
import product29 from '../assets/Images/groom3.webp';
import product30 from '../assets/Images/groom4.webp';
import product31 from '../assets/Images/supply3.webp';
import product32 from '../assets/Images/supply4.webp';
import product33 from '../assets/Images/toy3.webp';
import product34 from '../assets/Images/toy4.jpg';
import product35 from '../assets/Images/treat3.jpg';
import product36 from '../assets/Images/treat4.jpg';
import product37 from '../assets/Images/groom5.webp';
import product38 from '../assets/Images/groom6.webp';
import product39 from '../assets/Images/groom7.webp';
import product40 from '../assets/Images/groom8.webp';
import product41 from '../assets/Images/groom9.webp';
import product42 from '../assets/Images/groom10.jpg';
import product43 from "../assets/Images/access5.webp";
import product44 from "../assets/Images/access6.webp";
import product45 from "../assets/Images/access7.webp";
import product46 from "../assets/Images/access8.webp";
import product47 from "../assets/Images/access9.webp";
import product48 from "../assets/Images/access10.webp";
import product49 from '../assets/Images/toy5.webp';
import product50 from '../assets/Images/toy6.webp';
import product51 from '../assets/Images/toy7.webp';
import product52 from '../assets/Images/toy8.webp';
import product53 from '../assets/Images/toy9.webp';
import product54 from '../assets/Images/toy10.webp';
import product55 from '../assets/Images/supply5.webp';
import product56 from '../assets/Images/supply6.webp';
import product57 from '../assets/Images/supply7.webp';
import product58 from '../assets/Images/supply8.webp';
import product59 from '../assets/Images/supply9.webp';
import product60 from '../assets/Images/supply10.webp';
import product61 from '../assets/Images/treat5.jpg';
import product62 from '../assets/Images/treat6.webp';
import product63 from '../assets/Images/treat7.webp';
import product64 from '../assets/Images/treat8.webp';
import product65 from '../assets/Images/treat9.webp';
import product66 from '../assets/Images/treat10.webp';


export const products = [
    {
        _id: "aaaaa",
        image: [product1],
        fname: "Royal Canin Puppy, 2-12 Months Puppy, Medium Adult Weight(11-25kg), Wet Food for Puppy, Meat and Nutrition",
        name: "Royal Canin for Puppy",
        brand: "Royal Canin",
        price: 3004,
        ratings: "167k",
        category: "Food",
        subCategory: "Puppyfood",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ ROYAL CANIN® Medium Puppy food is suitable for puppies between 2 and 12 months old that will have a medium-sized adult weight between 11kg to 25kg.",
        description2: "✅ ROYAL CANIN® Medium Puppy food contains an increased protein content to help support healthy, muscular, and skeletal growth during the relatively short growth period. Antioxidants are included to support your puppy's natural defences which can be a particular challenge during this life stage.",
    },
    {
        _id: "baaaa",
        image: [product27],
        name: "Eye & Ear Pads",
        fname: "Pet Clean Primrose Oil Eye & Ear Pads - Gentle Care for Dogs - 50 Count (Pack of 1)",
        brand: "",
        price: 279,
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["50 count", "100 count"],
        description1: "✅ Gentle Care for Eyes and Ears: Specially formulated to clean, deodorize, and dry your pet's ears and eyes. These wipes provide a soothing and effective solution for maintaining eye and ear hygiene, ensuring your pet's comfort and well-being. Prevent Infections and Reduce Buildup: By using Pet Clean Ear and Eye Wipes regularly, you can prevent infections and reduce wax and debris buildup in your pet's ears and eyes.",
        description2: "✅ These wipes offer a convenient and safe way to remove tear stains, keeping your pet's delicate areas clean and healthy. Veterinarian-Recommended Quality: Recommended by veterinarians, reflecting their high-quality and effectiveness. Give your pet the best care possible with these veterinarian-recommended wipes.",
    },

    {
        _id: "caaaa",
        image: [product51],
        name: "Petsware Toy",
        fname: "PETSWARE Attractive Dog Toys for Large Dogs & Accessories Toy for Puppies, Pets, Puppy, Medium & Adults, chew Rope Small pups for Playing & Chewing for Labrador Combo (Yellow sage (3 Rings)",
        brand: "",
        price: 249,
        ratings: "667",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L"],
        description1: "✅ 3 INTERWINED RINGS COMBO. VIRTUALLY INDESTRUCTIBLE : 100% Non-toxic Cotton - when chewed helps to maintain dental hygiene by flossing the teeth and massaging the gums. Machine washable so your house stays free of harmful bacteria. 3 different toys to choose from - so it will take 4 times longer for the toy to wear out. Bob Barker Blue is not just to show off but to make it really easy to find when you want to play or it’s time to go home from the park.", 
        description2: "✅ HAND MADE IN INDIA WITH CARE: Made with a mix of cotton and Polyester fibres for shine and extra strength. Hand picked 'Bob Barker Blue' Colour and packed with care to brim you with excitement and make your fall in love with you ever so easily. Enjoy!",
    },

    {
        _id: "daaaa",
        image: [product2],
        fname: "Pedigree Puppy Dry Dog Food, Complete & Balanced food for Dogs, Chicken & Milk 3kg Pack",
        name: "Pedigree for Puppy",
        brand: "Pedigree",
        price: 1199,
        ratings: "10k",
        category: "Food",
        subCategory: "Puppyfood",
        featuredproduct: true,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ PEDIGREE complete and balanced dog food for puppies is a wholesome meal packed with essential nutrients vital to the healthy growth of your pet. PEDIGREE, with the goodness of cereals, chicken, meat, and the nutrients, blend into a tasty and healthy treat for your little one.",
        description2:  "✅ With PEDIGREE, you are sure to see the 5 Signs of Good Health in your pet if you feed him as per the given feeding guidelines. These signs include improved natural defence (from Vitamins (Vit E) and Minerals); Strong Muscles (from Protein); Optimal Digestion of Nutrients; Strong Bones and Teeth (from Ca:P ratio & levels); Healthy Skin and Coat (from blend of Zinc and Omega Fatty Acids).",
    },
    {
        _id: "eaaaa",
        image: [product25],
        name: "Dog Nail Cutter",
        fname:"PetVogue Dog Nail Cutter Clipper And Filer, Claw & Nails Clippers Grinder Grooming Trimmer For Small, Medium, Large Dogs, Red",
        price: 250,
        brand: "",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ Stainless steel Sharpness blades: The pet nail clippers are made out of high quality 4.0 mm thick stainless steel sharp blades, it is powerful enough to trim your dogs or cats nails with just one cut, these durable clippers won't bend, scratch or rust, and the blades still keep sharp even through many sessions on dog tough nails.",
        description2: "✅ Secure Grip Rubber Coated Non-Slip Handles: Ergonomic 'Easy-Grip' Handle Design with Extra-Long Non Slip Handles, Perfect For Small & Large Hands.",
    },

    {
        _id: "faaaa",
        image: [product61],
        name: "Dog Treats",
        fname: "ChewersChewers Oven Baked Real Mutton Adult Dog Biscuits, Mutton Flavour, Dog Treat 1 Kg",
        price: 220,
        brand: "Chewers",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["500gm", "1kg", "1.5kg"],
        description1: "✅ Simple and pure: Made with wholesome ingredients that allow for easy digestion with nothing artificial, delicious mix of flavors from locally sourced ingredients lets you give even the pickiest dogs a worthy treat, our oven baked biscuits are all natural, protein-packed treat that comes from fresh butter as first ingredient, these are enriched with vitamins, calcium, omega 3, omega 6, brewers yeast and few other nutrients for better immunity and health.",
        description2: "✅ Free from: These tasty dog treats are free from gmos, preservatives, or artificial colourings. All sizes: These delicious biscuits are slow oven baked making them crunchy and easily breakable, suitable for smaller and larger dogs of all ages.",
    },

    {
        _id: "gaaaa",
        image: [product4],
        fname: "Royal Canin Medium Adult Dog Food(11-25kg), Size Health Nutrition, Meat Flavour (12Months), 4kg Pack",
        name: "Royal Canin for Adult",
        price: 3204,
        brand: "Royal Canin",
        ratings: "111k",
        category: "Food",
        subCategory: "Adultfood",
        featuredproduct: false,
        bestseller: false,
        sizes: ["2kg", "4kg", "6kg"],
        description1: "✅ ROYAL CANIN® Medium Adult is specially formulated with the nutritional needs of your medium-sized adult dog in mind and is suitable for dogs aged 1-7 years that weigh between 11kg-25kg. ROYAL CANIN® Medium Adult contains an exclusive antioxidant complex, as well as nutrients like manno-oligo-saccharides, to help support your dog's natural defences, allowing it to maintain a healthy lifestyle.",
        description2: "✅ Thanks to an exclusive formula which includes very high quality protein. ROYAL CANIN® Medium Adult also helps to support optimal digestibility, this allows your dog to effectively absorb nutrients.",
    },
    {
        _id: "haaaa",
        image: [product5],
        fname: "Stainless Steel Bowl for Dogs Feeding - 700ml, Medium (Gray) Color, Non-Skid Rubber Bottom Food/Water Bowl, Non-Toxic & 100% Safe for dogs ",
        name: "Feeding Bowl",
        brand: "",
        price: 199,
        ratings: "543",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L"],
        description1: "✅ Every pet owner wants to give their pets the best quality product so as to keep them healthy and happy. By selecting BASIL bowls they are assured to get all the necessary requirements in one product as our products are free from all doubts and complete on purity. Basil bowls are high on quality and assure you to be made using best ingredients with pure intention of Pet Welfare.",
        description2: "✅ Our bowls are 100% food grade and last long for the pet’s lifetime, durability is the first priority and we stand just at the same point of what our customers expect from a product. We work on international standards to provide our clients with best in class products.",
    },
    {
        _id: "iaaaa",
        image: [product6],
        name: "Toy Ball",
        fname: "Pet Central Interactive Toy Ball for Dogs Bouncing Chew Ball for Aggressive Dogs (Green) Fun Ball Medium and Large Dogs 5.5 X 5.5",
        price: 300,
        brand: "",
        ratings: "667",
        category: "Toys",
        subCategory: "",
        featuredproduct: true,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ Just the glimpse of a Chuckit! toy is enough to excite the 'fetch fanatic dog'. The bright colors signal an adventure with major playtime to come. Chuckit! performance toys are designed to take interACTION to the next level.",
        description2: "✅ These dynamic products are not intended to be solo play toys. Built on innovation and ergonomic design, Chuckit! has revolutionized the classic game of fetch. This enhanced experience encourages more fun play. Pioneering play since 1998, the human-animal bond is at the heart of every Chuckit! toy we make. Sharing the exhilaration elevates playtime to a new standard. we are proud to bring MORE WAYS TO PLAY!",
    },
    {
        _id: "jaaaa",
        image: [product28],
        name: "Dog Treats",
        fname: "Meat Up Dog Treats Pressed Chew Bones, 15.24 Cm, Pack Of 3 (Buy 1 Get 1 Free) For Above 3 Months",
        price: 299,
        brand: "Meat up",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["100gm", "250gm"],
        description1: "✅ Safe and healthy bones for your dog. Made in a pet friendly design. All breed formula. Suitable for pets over 3 months. material_features:non-vegetarian. form_factor:dry",
    },

    {
        _id: "kaaaa",
        image: [product7],
        name: "Water Dispenser ",
        fname: "Pet Water Dispenser Station - 11L Bottle for Large Dog Automatic Gravity Water Drinking Fountain Bottle Bowl Dish Stand",
        price: 1005,
        brand: "",
        ratings: "145",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["3L", "5L"],
        description1: "✅ Loop Water Store, made of high-quality plastic, is a premium, modern water dispenser and provides your cat, dog, or small animal with fresh water whenever it is thirsty. The transparent container of the dispenser allows easy checking of the water content level. ",
        description2: "✅ The integrated rubber non-slip rim underneath gives the bowl extra stability and sturdiness and ensures also that it stays in place on smooth floors. Finally, the Loop dispenser is made from washable plastic which makes it easy to clean.",
    },
    {
        _id: "laaaa",
        image: [product8],
        name: "Hair Brush ",
        fname:"Slicker Dog Comb Brush, Pet Grooming Brush Daily Use to Clean Loose Fur & Dirt Great for Dogs with Medium Long Hair Dog Hair Deshedding Brush Dog Hair Brush",
        price: 400,
        brand: "",
        ratings: "178",
        category: "Grooming",
        subCategory: "Brush",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L"],
        description1: "✅ Make pet grooming easy with Trixie Double Sided Brush, Pin + Bristles. Maintain a healthy-looking coat by daily grooming your pet. The brush is a dual-purpose pin and bristle grooming brush. It comes with a wooden handle for a good grip.",
        description2: "✅ The bristle's side helps remove the hair from fabric and clothes. The pin side removes dead hair from your pet's undercoat. The brush helps to promote a shiny and healthy coat. Massages and pulls out dead hair from the undercoat and topcoat.",
    },
    {
        _id: "maaaa",
        image: [product9],
        name: "Body Belt ",
        fname: "Dog Harness Chest Body Belt for Dogs, Reflective Dog Vest for Large Dogs - Labrador, Retriever, Rottweiler (XL - Above 35kg Dogs, Black with Pet Name)",
        price: 700,
        brand: "",
        ratings: "40k",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "M", "L", "XL"],
        description1: "✅ Designed for active dogs that are always out in front (you know the kind), the Journey Air takes the all the best features of the original—the athletic cut, the convenient handle on the back—and ups the ante.",
        description2: "✅ It’s a breathable harness featuring a deep V-neck that keeps the shoulders free (and shows off that chest hair), plus features a wide, padded chest plate that helps cut down on strain to the neck. And with rust-free all-aluminum hardware, it comes in at a featherweight 230g., so your dog can forget the harness and focus on more important things, like smelling stuff, running, chasing things, and smelling stuff. We think this is the beginning of a beautiful friendship.",
    },
    {
        _id: "naaaa",
        image: [product31],
        name: "Dog Serum for Tangle-Free",
        fname: "Bark Out Loud by Vivaldis - Dog Serum for Tangle-Free, Linseed, Coconut & Grapeseed Oil for Shiny Coats, Anti Frizz Formula to Manage Knots (100 ml)",
        price: 389,
        brand: "Bark Out Loud",
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["100ml", "250ml"],
        description1: "✅ Natural luxe sheen: The Dog serum is a soothing formula enriched in oil components and designed to promote a healthy coat and add a natural sheen to your pet’s fur. The fur is strengthened with shine and volume. Hydration custodian: Made with premium plant extracts, linseed oil, and coconut oil work in harmony to moisturize and nourish the coat.",
        description2: "✅ Linseed oil with its omega power lends a lustrous coat. Coconut oil helps maintain the H2O levels in the coat. Knot-free bliss: The serum is renowned for untangling the knots, reducing frizz, and making brushing the hair a breeze! Linseed oil, grape extract, and coconut oil reduce shedding and enrich coat management. A relaxing formula for detangling!",
    },
    {
        _id: "oaaaa",
        image: [product10],
        name: "Neck Belt ",
        fname: "Dog Collar Belt with Name Customized for Large, Medium, and Small Dogs, Neck Collar with Personalized Dog Name (Large, Red with Diamonds)",
        price: 439,
        brand: "",
        ratings: "35k",
        category: "Accessories",
        subCategory: "",
        featuredproduct: true,
        bestseller: false,
        sizes: ["S", "M", "L", "XL"],
        description1: "✅ Collar & leash training is a critical aspect of puppy obedience and development. You know you can control your dog with a simple command and it will understand and adhere. But a collar, leash, or harness isn’t just some fabric and metal accessory your dog needs, it's a part of your dog's personality.",
        description2: "✅ This exhaustive range of colorful collars is waiting for your dog and you to choose. No matter how big or small your dog is, no matter what your dog’s tastes are, you’re sure to find something that you’ll want. The range of leashes and harnesses is equally huge. Make your walks enjoyable & stylish!",
    },
    {
        _id: "paaaa",
        image: [product11],
        name: "Himalaya Shampoo ",
        fname: "Himalaya Erina - Ep Shampoo For Dogs, Tick and flea Management, Lemon Fragrance, 200Ml",
        price: 365,
        brand: "Himalaya",
        ratings: "68k",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["100ml", "200ml", "500ml"],
        description1: "✅ Himalaya Erina EP Shampoo for Dogs & Cats helps in tick and flea management for your furry friend. Prevents ectoparasites: Erina EP controls ectoparasites (external parasites) like ticks, fleas and lice in pets. There’s no pain like tick and flea, right? We get you. That’s why, we at Petsy, have a wide range of tick and flea products to combat every one of those pesky insects.",
        description2: "✅ So, what do you need in your tick and flea grooming kit? First off, flea and tick shampoo for cats, such as the wahl flea and tick shampoo is an absolute must-have, followed by a flea comb, flea and tick collar for cats, and tick spot-on.",
    },
    {
        _id: "qaaaa",
        image: [product12],
        name: "Himalaya Healthy Treat",
        fname: "HIMALAYA Healthy Dog Biscuits for Adult, Dog Treats with Health Benefits, Supports Skin Health and Fitness with Chicken (400gm)",
        price: 162,
        brand: "Himalaya",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["200gm", "400gm"],
        description1: "✅ Healthy treats support skin health and promote overall fitness in adult dogs Fortified with Flaxseed, which supports skin health Healthy treats are tasty, highly relished, and help in bonding with your pet Two to eight treats daily depending on the size of the dog Looking for the best dog biscuits in India?",
        description2: "✅ At Petsy, we stock an extensive collection of delectable dog cookies and dog biscuits to satisfy that dripping drool. Get the best dog biscuits for every occasion - whether for snack time or as a tasty meal topper, Petsy is all about irresistible drool-worthy yummies.",
    },
    {
        _id: "raaaa",
        image: [product13],
        fname : "Pedigree PRO Adult (9 Months Onwards) Small Breed Dry Dog Food, 3 kg, High-Protein Dog Food, Expert Nutrition with 33%* More Nutrients",
        brand: "Pedigree Pro",
        name: "Pedigree Pro for Adult",
        price: 1140,
        category: "Food",
        subCategory: "adult food",
        ratings: "80k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ Different dog breeds have different nutritional needs, depending on their size and respective weight. Small breed dogs are prone to teeth and gum diseases, which is why nutrient-rich meals like Pedigree PRO help support their dental health. On the other hand, Omega fatty acids and Protein help maintain bone strength and agility in bigger dog breeds.",
        description2: "✅ Pedigree PRO dog food range of products combine high-quality ingredients with the science developed with nutritionists and veterinarians at the WALTHAM Centre. Everything we do at Pedigree is for the love of dogs because dogs bring out the good in us and Pedigree Pet food brings out the good in them.",
    },
    {
        _id: "saaaa",
        image: [product26],
        name: "Toys set",
        fname: "Agirav Tail Dog Toys + Dog Chew Toys + Rope Toys + Dog Toys for Small to Medium Dog + Tug Toy + Dog Toy Pack of 7",
        price: 258,
        brand: "",
        ratings: "38",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ Great Combination of dog rope toys(single carrot, corn stick, Cosco Ball knot dumbbell, Rope Ball, Slipper, 2 Knot Rope, Tug of War Ball ), meet daily needs, and we are sure that your dogs will love these toys Outstanding Quality.",
        description2: "✅ These chew toys are made of thick and tight cotton ropes which are non-toxic and durable, absolutely safe for your dogs. Do Exercise: Play catch or tug of war games with your four legged friends, it will bring you two closer together, and your dogs should be more happy and healthy.",
    },
    {
        _id: "taaaa",
        image: [product14],
        fname: "Pedigree PRO Puppy (3 to 18 Months) Large Breed Dry Dog Food, 3 kg, High-Protein Dog Food, Expert Nutrition with 33%* More Nutrients",
        brand: "Pedigree Pro",
        name: "Pedigree Pro for Puupy",
        price: 930,
        category: "Food",
        subCategory: "puppies food",
        ratings: "82k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ Pedigree Pro Puppy large breed Range dog food fulfills the special needs of your dog. The range provides expert nutrition combining high quality ingredients with the science developed by our veterinarians and nutritionists at WALTHAM- the worlds leading authority on pet care and nutrition.",
        description2: "✅ When you buy Pedigree dog food, make sure it is properly sealed On opening the pack. Store Pedigree dog food in an air-tight container, in a cool and dry place, away from sunlight",
    },
    {
        _id: "uaaaa",
        image: [product29],
        name: "Hair Brush",
        fname:"Depets Self Cleaning Slicker Brush, Pet Grooming Shedding Brush for Dogs - Easy to Remove Loose Undercoat, Pet Massaging Tool Suitable for Pets with Long or Short Hair color may vary",
        price: 200,
        brand: "",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ Clean Pets, Clean House. emily cat & dog brush for shedding can easily remove loose hair, shedding mats, tangled hair, dander and dirt of your lovely pet, which not only keep your pet clean, but also provide you with a clean and hygienic home environment.",
    },
    {
        _id: "vaaaa",
        image: [product15],
        fname: "Drools Adult Dry Dog Food ,Chicken and Egg Flavour 15kg + 3kg Free Pack 100% Nutrition and Healty food",
        brand: "Drools",
        name: "Drools for Adult",
        price: 667,
        category: "Food",
        subCategory: "adult food",
        ratings: "95k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["5kg", "10kg", "15kg"],
        description1: "✅ Real chicken, our #1 ingredient, helps in maintaining lean muscles of your dog for a top body condition. A great combination of ingredients with the goodness of Vitamins and Minerals that maintain strong bones and a healthy digestive system.",
        description2: "✅ Protein enriched food with the proper ratio of nutritional elements that provide optimum health beneﬁts to your pet. Specially designed kibbles help to control tartar build-up Ideal for all breeds of dogs.",
    },
    {
        _id: "waaaa",
        image: [product32],
        name: "Pet Area Freshener",
        fname: "Odo-Rite Pet Area Freshener- 200ml | Pet Odour Remover | Pet Safe & Child Safe | Bio Technological Based | Skin Safe | Urine Smell Remover | Can Be Used on All Surface",
        price: 289,
        brand: "Odo Rite",
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["100ml", "200ml"],
        description1: "✅ Having a pet and keeping the home clean is quite a challenge, and choosing products that are safe for your pets is an even bigger struggle. Odo-Rite presents a remarkable solution in eliminating any kind of odour and urine smell of your pets, without compromising their health. This spray can be used for your dog’s / cat’s bedding / cage to remove any kind of lingering odour, poop / urine smell or simply for any other area of your house.",
        description2: "✅ Odo-Rite Pet Area Freshener provides a deep cleaning action and eliminates odor in a natural way. It begins working in 30 seconds and continues working for more than 12 hours, till all the odor producing compounds in the organic material are broken down, leaving the space smelling fresh.",
    },
    {
        _id: "xaaaa",
        image: [product16],
        fname: "Drools Puppy Dry Dog Food ,Chicken and Egg Flavour 10kg Pack 100% Nutrition and Healthy food",
        brand: "Drools",
        name: "Drools for Puppy",
        price: 438,
        category: "Food",
        subCategory: "puppies food",
        ratings: "103k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["5kg", "10kg", "15kg"],
        description1: "✅ Drools Chicken and Egg Adult Dry Dog Food offers a complete and balanced nutritional diet for your dog. We use Real Chicken which is our #1 ingredient, making our food rich in protein which helps in maintaining lean muscles for top body condition of your dog.",
        description2: "✅ It boosts digestive ability and strengthens immune system to keep them active and healthy all day long. All the raw materials used are thoroughly checked to maintain the quality and safety of our food.",
    },

    {
        _id: "yaaaa",
        image: [product62],
        name: "Dog Treats",
        fname: "Bark Out Loud by Vivaldis - Mini Fishes (Salmon)| No Grain & Hypoallergenic Spanish Treats for Dogs- 100gms",
        price: 250,
        brand: "Bark Out Loud",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: true,
        bestseller: false,
        sizes: ["100gm", "200gm"],
        description1: "✅ GRAIN FREE – Indulge in premium quality treat made in Spain with love for your Doggy’s good health! The treats are protein-rich made with Salmon and Peas with aromatic herbs that are so delicious that your pet goes Woof! HYPOALLERGENIC – Mini Fishes are delicious rewards formulated for pets with food intolerances and to support skin function- with a great taste your dog will love.",
        description2: "✅ POWERPACKED – With added Vitamin E for a healthier immune system, muscles, heart health, liver, nerve cell membranes and healthy skin and coat for dogs. An added benefit of rich protein for an extra bark in the day!",
    },

    {
        _id: "zaaaa",
        image: [product17],
        fname: "Pedigree Adult Mini (9+ months) Dog food, Dry Dog Food, Lamb & Veg Flavour, 2.7 kg Pack",
        brand: "Pedigree",
        name: "Pedigree Puppy",
        price: 599,
        category: "Food",
        subCategory: "puppies food",
        ratings: "15k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "2.7kg", "5kg"],
        description1: "✅ SMALL BITES FOR SMALL MOUTHS: Adequate size dry dog food bites for their small mouth of small and medium sized breed dogs to help with easier chewing and improved long term dental health.",
        description2: "✅ QUALITY PROTEIN: Pedigree Small Dog Food contains adequate amount of protein that helps to support healthy muscles to keep dogs active and agile",
    },
    {
        _id: "abaaa",
        image: [product33],
        name: "Toy Ball",
        brand: "",
        fname: "The Dogs Company The Pets Company Natural Rubber Spiked Ball Dog Chew Toy, Puppy Teething Toy, 3 Inches",
        price: 189,
        ratings: "56",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ SUPER SAFE NON-TOXIC Our Rubber Dog Chew Toys are made of hard natural rubber making it 100% safe for your pets. SUPER DURABLE and LONG LASTING.These nearly indestructible dog toys will entertain your dog for hours unlike squeaky or plush toys that get destroyed in minutes.",
        description2: "✅ DENTAL CLEANING The spikes or soft grooves on the surface helps in cleaning and massaging the gums hence controlling plaque and tartar build up.",
    },
    {
        _id: "acaaa",
        image: [product18],
        fname: "Pedigree High Protein Adult Dry Dog Food Beef Lamb Flavor Dog Kibble, 18lb Bag, 2kg Pack, Resy Pollo",
        brand: "Pedigree",
        name: "Pedigree Adult",
        price: 1599,
        category: "Food",
        subCategory: "Adult food",
        ratings: "99k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["2kg", "3kg", "5kg"],
        description1: "✅ The PEDIGREE line of nutritionally balanced food helps ensure your dog can live their happiest and healthiest life. Our protein rich recipe is made with real red meat, and 25% more protein than Adult Complete Nutrition. It’s always 100% complete and balanced for canines with no added sugar, no artificial flavors, and no high fructose corn syrup.",
    },
    {
        _id: "adaaa",
        image: [product30],
        name: "Bath Gloves",
        fname:"Aufew Magic Pet Grooming Gloves Dog Bathing Scrubber Gloves, Heat Resistant Eco-Friendly Silicone Hair Removal Gloves with High Density Teeth for Dogs, 2 Piece",
        price: 159,
        brand: "",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ Premium Material - Dimension 13.8in * 5.9in. The magic gloves are made entirely of eco-friendly silicone, which is with superior elastic and soft property, no easy to tear. High Density Brush Heads - There are over 3,000 15mm brush heads spread over the glove palm to ensure easier hair grooming for your dogs or cats without any uncomfortable feeling.",
        description2: "✅ Heat Resistant - Excellent heat resistance up to 501°F, so the grooming gloves can be sterilized with boiling water while having a pet bathing. Never worry about getting scalded.",
    },
    {
        _id: "aeaaa",
        image: [product49],
        name: "Dog Toys",
        fname: "Pet Central Interactive Dog Toys – Suction Cup Dog Chew Toy for Aggressive Chewers – Treat Dispensing Squeaky Dog Toy for Stimulation and Self-Playing – Tug of War Rope with Teeth Cleaning Ball",
        price: 999,
        brand: "",
        ratings: "667",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ The Ideal Choice: If you are looking for new ways to prevent your pet from ruining your couch or chewing on your shoes, the Pet Central suction cup dog tug toy is the perfect choice to keep your beloved pet busy for hours and prevent boredom!",
        description2: "✅ High-Quality Materials: Our suction cup dog ball is made with high-quality TPR material, which is strong and durable, built to withstand the biting force even of the most aggressive chewers. The dog toy is also safe, non-toxic and easy to clean.",
    },

    {
        _id: "afaaa",
        image: [product55],
        name: "Neem Anti Tick and Flea Dog Shampoo",
        fname: "Dogz & Dudez Natural Neem Anti Tick and Flea Dog Shampoo 200ml | for All Types of Dog Shampoo | Anti Itch Shampoo for Dog with Neem and Lemongrass | Paraben Free, Ph Balanced, Cruelty Free",
        price: 299,
        brand: "Dogz & Dudez",
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["100ml", "200ml"],
        description1: "✅ Break the life cycle of ticks & fleas by using the natural dog dog shampoo for labrador, german shephard. An ideal solution, especially concocted for your pet to get rid of the bloodsuckers. Natural & potent blend of formula developed using plant-based ingredients like the extracts of lemongrass and natural ayurveda herb neem to give your dog a healthy lifestyle.",
        description2: "✅ Best tick shampoo for dogs. Water-like texture in our efforts to keep it natural, gentle and chemical free, the shampoo resulted to be very light and hence, has a water-like texture. This make the shampoo ticks and fleas remover for dogs",
    },

    {
        _id: "agaaa",
        image: [product19],
        fname: "Drools Puppy Dry Dog Food Chicken and Egg, 3kg with Free 1.2kg, Total 4.2 kg Pack",
        brand: "Drools",
        name: "Drools Puppy",
        price: 679,
        category: "Food",
        subCategory: "puppies food",
        ratings: "67k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ A complete and balanced nutrition helps in puppies’ growth and development. DHA helps in Brain Development. Highly palatable and easily digestible. Vitamins, Antioxidants and other essential ingredients strengthen immune system. The kibbles help to control tartar build-up ; Suitable for all breeds.",
    },
    {
        _id: "ahaaa",
        image: [product35],
        name: "Dog Treats",
        fname: "PUREPET Dog Treat Munchy Sticks, Chicken Flavour 400G Pack, All Life Stages",
        price: 179,
        brand: "Purepet",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["200gm", "400gm"],
        description1: "✅ Munchy Sticks are long lasting chicken ﬂavour treats that dog loves. It is made from quality rawhide. Ideal for all breeds. Helps in reducing tartar. Promotes healthy teeth and gums",
    },
    {
        _id: "aiaaa",
        image: [product20],
        fname: "Drools 100% Vegetarian Adult Dog Dry Food Pack of 3kg + 1.2kg Free ",
        brand: "Drools",
        name: "Drools Adult",
        price: 909,
        category: "Food",
        subCategory: "Adult food",
        ratings: "49k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ Introducing Drools 100% Vegetarian Adult Dog Dry Food, a premium choice for conscientious pet owners seeking nutritious and wholesome options for their furry companions.",
        description2: "✅ Specially formulated for adult dogs, this vegetarian dog food in India provides a balanced diet that supports overall health and vitality. Crafted with high-quality, plant-based ingredients, it ensures your dog enjoys a meal that is both delicious and nourishing.",
    },

    {
        _id: "ajaaa",
        image: [product56],
        name: "Paws Cream for Dogs",
        fname: "Papa Pawsome Soft Paws Cream for Dogs | Natural, Lick-Safe | Paw Butter | Heals, Moisturizes, Softens Dry Chapped Paws, Cracked Elbows, Nose | Castor Oil, Tea Tree Oil, Vitamin E |Safe for Puppies| 25g",
        price: 249,
        brand: "Papa Pawsome",
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["25gm", "50gm", "100gm"],
        description1: "✅ USP: This paw cream provides natural nourishment to the dogs sensitive paw pads, snout and elbows with natural healing benefits. It contains vitamin e and tea tree essential oil for extra moisturizing that heals cracked paws, elbow pads and snouts, moisturises dry skin.",
        description2: "✅ 100 % Safe To Lick: The product is made with natural olive oil, flaxseed oil, castor oil and beeswax that makes it 100% safe for your pet to lick. Ingredients: Beeswax, olive oil, flaxseed oil, castor oil, peppermint essential oil, tea tree essential oil, vitamin e; Essential oils: Peppermint & tea tree",
    },
    
    {
        _id: "akaaa",
        image: [product21],
        fname: "Pedigree Pro Adult Chicken Large Breed, Dry Dog Food (18 Months Onwards), 3 Kg Pack",
        brand: "Pedigree Pro",
        name: "Pedigree Pro for Adult",
        price: 457,
        category: "Food",
        subCategory: "Adult food",
        ratings: "34k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ ADAPTED KIBBLE SIZE: Pedigree PRO Dry Dog Food for Adult Large Breed Dogs is packed with specially designed adapted kibbles. SUPERIOR INGREDIENTS: It is formulated with superior ingredients & high protein, for your dog's overall well-being.",
        description2: "✅ EXPERT NUTRITION: Pedigree PRO adult dog food contains 33%* more nutrients (*Compared to Pedigree Adult Chicken & Veg Dry Dog Food).",
    },
    {
        _id: "alaaa",
        image: [product36],
        name: "Dog Treats",
        fname: "Milky Chew Stick Style Treats for Dogs of All Ages and Sizes, Premium Milk Flavored Dog Snacks, Rawhide Free, Nutritional Benefits, Strengthen Bones and Teeth",
        price: 349,
        brand: "Milky chew",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["100gm", "200gm"],
        description1: "✅ Milky Chew stick-style dog treats with premium milk flavour are suitable for all dog sizes and ages; these dog treats have the right amount of protein, calcium, and vitamins. Treats are rawhide-free, which makes them different from ordinary treats.",
        description2: "✅ Treats for dogs are packed with all the nutritional benefits that maintain tooth health and promote fresh breath. They are palatable, and contains healthy milk safe to consume. Treats are premium, with a delicious milk flavour, and provide excellent nutrition for dogs with the finest ingredients that are highly digestible",
    },
    {
        _id: "amaaa",
        image: [product22],
        fname: "Pedigree PRO Puppy (2 to 9 Months) Small Breed Dry Dog Food, 3 kg, High-Protein Dog Food, Expert Nutrition with 33%* More Nutrients",
        brand: "Pedigree Pro",
        name: "Pedigree Pro for Puppy",
        price: 1140,
        category: "Food",
        subCategory: "puppies food",
        ratings: "36k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ If you love to see your small-breed pet puppy happy, cheerful, and full of energy every single day, then feed him/her the Pedigree PRO Expert Nutrition for Small Breed Puppy Dry Dog Food three to four times a day.",
        description2: "✅ By feeding this dog food, you can ensure a Strong Immune System and an Improved Digestive Health. Also, it contains Proteins to promote growth.",
    },
    {
        _id: "anaaa",
        image: [product37],
        name: "Dog Flea Remover",
        fname:"Foodie Puppies Pet Flea Comb for Dog - (Flea Comb - Large) | Stainless Steel Fine Tooth Flea Lice Tear Stain Remover Comb | Hair Nit Comb For Head Nit Treatment Removes Head Nits (Large)",
        price: 198,
        brand: "",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ Best tool to remove fleas, flea eggs, debris and dust - our flea comb has closely-spaced metal pins which easily remove fleas, flea eggs, and debris from your pet's coat works great on dogs with all hair types!.",
        description2: "✅ Easy- grip handle for safe and comfortable Removes loose fur and leaves a clean and shiny coat Massaging brush. Don't pull out the hair forcibly to avoid causing pain of your pet.",
    },
    {
        _id: "aoaaa",
        image: [product23],
        fname: "Royal Canin Golden Retriever Adult Dry Dog Food 3kg pack Meat Over 15 months dog",
        brand: "Royal Canin",
        name: "Royal Canin Adult",
        price: 2596,
        category: "Food",
        subCategory: "adult food",
        ratings: "131k",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ Suitable for dogs over 15 months old, ROYAL CANIN Golden Retriever Adult is specially formulated with all the nutritional needs of your adult dog in mind. ROYAL CANIN Golden Retriever Adult contains omega-3 fatty acids, including EPA and DHA, and borage oil.",
        description2: "✅ These nutrients all help to support a healthy skin barrier function which in turn contributes to the healthy appearance of your dog's coat. ",
    },
    {
        _id: "apaaa",
        image: [product34],
        name: "Toy Ball",
        fname: "Foodie Puppies Latex Rubber Squeaky Dog Chew Ball Toy - (Claw Ball, Small) for Small to Medium Dogs & Puppies | Safe, Durable, Puppy Paw for Playing & Fetching Toy | Reduce Anxiety (Diameter: 6.5cm)",
        price: 190,
        brand: "",
        ratings: "667",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ NATURAL LATEX RUBBER: Safe materials, non-toxic & no harmful to pets safe for your pets to chew and play. These toys have a soft-touch texture that dogs love. Any toys are not indestructible, only supervised play and discard and timely replacement of the frayed or worn toys.",
        description2: "✅ FUNNY SQUEAKY TOYS: Each squeaky dog toy with a fun squeaker inside to entice your pets. Makes a squeaky good sound when squeezed, a loud squeaky appeals to your dog’s natural instincts to hunt. The funny squeak can attract your dog's interest and give them a lot of fun.",
    },

    {
        _id: "aqaaa",
        image: [product57],
        name: "Dog Paw Cleaning Foam ",
        fname: "Foodie Puppies Dog Paw Cleaning Foam (Lavender) with Silicone Brush - 150ml | Paw Cleaner for Dog Foot Scrubber Cleaning Brush | Fortified with Tea Tree Oil and Aloe Vera Extract",
        price: 238,
        brand: "",
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: true,
        bestseller: false,
        sizes: ["150ml", "250ml"],
        description1: "✅ KEEP PET HEALTHY Effectively solve foot skin problems, long term use can prevent dry foot cracking. Plant recipe deep, cornified gentle not stimulating, harmless licking give pet health care. WITH MASSAGE BRUSH There is a massage brush at the nozzle, which can clean the soles of the feet while massaging the pet.",
        description2: "✅ CONVENIENT TO USE Compact and convenient, put into bag does not take up space, can used anytime and anywhere. SILICON SCRUBBER BRUSH Our detachable silicon scrubber brush is super easy to clean and creates a thick lathered foam perfect for cleaning your cat's paws anytime, especially after walks.",
    },

    {
        _id: "araaa",
        image: [product24],
        fname: "Royal Canin Mini Adult Dry Dog Food 1kg pack Healthy food for adult mini breeds ",
        brand: "Royal Canin",
        name: "Royal Canin Adult",
        price: 822,
        category: "Food",
        subCategory: "adult food",
        ratings: "139k",
        featuredproduct: false,
        bestseller: true,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ Suitable for small breed dogs over 10 months old that weigh up to 10kg, ROYAL CANIN Mini Adult is specially formulated with all the nutritional needs of your adult mini dog in mind. Because small breed dogs like yours tend to have high energy needs.",
        description2: "✅ ROYAL CANIN Mini Adult is formulated with nutrients that help to meet those energy needs, whilst also helping your dog to maintain a healthy weight. ",
    },
    {
        _id: "asaaa",
        image: [product43],
        fname: "The Pets Company Folding Dog Poop Scooper, Pet Waste Potty Picker, Large, 24 Inches, Color May Vary",
        name: "Poop Scooper",
        brand: "",
        price: 400,
        ratings: "543",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L"],
        description1: "✅ Cleans your dogs poop hassle-free. Great tool to use indoor and outdoor. Easy to clean, just wash it off. One handed pick-up design allows you to clean up your dog's waste without even bending over or having to wrap your hands. Suitable for all dogs",
    },

    {
        _id: "ataaa",
        image: [product64],
        name: "Dog Treats",
        fname: "Chip Chops Chicken Codfish Rolls Dog Treat, Highly Nutritional & Digestible, Suitable for All Dog Breeds, Easy to Digest, No Artificial Flavors Added - 70gm",
        price: 199,
        brand: "ABK",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: true,
        bestseller: false,
        sizes: ["70gm", "100gm", "150gm"],
        description1: "✅ Highly Nutritional: Chip Chops Chicken and Codfish Rolls provide a rich source of protein, essential for maintaining your dog's muscle health and overall vitality. Easily Digestible: Formulated to be gentle on the stomach, these treats are suitable for dogs with sensitive digestive systems.",
        description2: "✅ No Artificial Flavors: Made with natural ingredients, these treats are free from artificial flavors, ensuring a wholesome and safe treat for your dog. Suitable for All Breeds: These treats are designed to meet the dietary needs of dogs of all breeds, making them a versatile choice for any dog owner.",
    },

    {
        _id: "auaaa",
        image: [product38],
        name: "Dog Massage Rubber",
        fname:"Foodie Puppies Pet Massage Rubber Bath Glove for Dogs | Grooming Shampoo Washing Soothing Bristles Hand Brush Comb - 1 Piece (Soothing Glove) (Pack of 1)",
        price: 190,
        brand: "",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ EFFECTIVE YET GENTLE: The soft rubber tips quickly scrub away dirt, dead skin and loose fur making it an excellent pet brush for grooming and bathing. It leaves pet skin clean and helps restore sheen and luster to the coat. Our handheld grooming tool won't pull on hair making it a perfect brush for pets with sensitive skin. Our dog bath brush also increases the effectiveness of shampoo lathering, allowing less product to go further. Achieve a deeper clean than shampooing alone.",
        description2: "✅ PETS LOVE THE MASSAGING BRISTLES: Your pet will now LOVE bath time! Turn grooming into a soothing massage for your pet that feels good, gets them clean and helps keep their skin and coat healthy. ",
    },
    {
        _id: "avaaa",
        image: [product44],
        fname: "Adjustable Double Dinner for Food and Water for Dog, with H-Base and Two Removable Stainless Steel Bowls 2 X 1500 Ml",
        name: "Adjustable Double Dinner Bowl",
        brand: "",
        price: 559,
        ratings: "543",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L"],
        description1: "✅ Adjustable height of the feeder lets the dog eat comfortably. Elevated feeder improve digestion and reduces strain on the muscle of the dogs. Heavy duty anti skid base ensures no tipping, spillage of food and water.",
        description2: "✅ Easy to clean, dishwasher safe - 2 stainless steel bowls. H base elevated adjustable strong stand with unique locking system keeps the bowls in place. Two Removable Stainless Steel Bowls 2 X 1500 ml",
    },

    {
        _id: "awaaa",
        image: [product45],
        fname: "Foodie Puppies Foot Washing Cup, Pet Paw Cleaner Portable Dog Paw Washer with Soft Silicone Bristles for Quickly Cleaning Pets Muddy Feet - Color May Vary (Paw Cleaner - Small)",
        name: "Foot Washing Cup",
        brand: "",
        price: 250,
        ratings: "543",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L"],
        description1: "✅ HIGH QUALITY MATERIAL - Foot washing cup is made from gentle silicone bristles which will help remove dirt and mud from your dog's paw cleans off mud, sand, dirt, ice melt &Prevents paw irritation due to salt or other contaminants in the environment.",
        description2: "✅ CLEAN PAWS GENTLY - The gentle silicone bristles on the bottle help loosen dirt and mud from your dog's paws. Keep the mess away from your car or home.",
    },

    {
        _id: "axaaa",
        image: [product58],
        name: "PET360 Digest+ Tummy Care ",
        fname: "PET360 Digest+ Tummy Care Formula | Gut Health Supplement for Dogs | Probiotics, Prebiotics, Digestive Enzymes & Vitamins for Improved Digestion & Immunity | Suitable for All Breeds - 100 gm",
        price: 253,
        brand: "Pet360",
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["50gm", "100gm"],
        description1: "✅ ENHANCES DIGESTIVE HEALTH: PET360 DIGEST+ Tummy Care Formula is an ideal gut health supplement powder for pets, featuring a powerful blend of probiotics, prebiotics, digestive enzymes, and vitamins. This formulation promotes healthy digestion, relieves from stomach discomfort and enhances nutrient absorption for pets.",
        description2: "✅ REDUCES INDIGESTION & LOOSE STOOLS: DIGEST+ is an essential pet supplement that effectively addresses indigestion and loose stool conditions. With its unique powerful blend, this supplement ensures your pet experiences a healthier digestive system..",
    },

    {
        _id: "ayaaa",
        image: [product50],
        name: "Plush Dog Toys",
        fname: "BarkButler Jum-BOH The Bear - Large Plush Dog Toy - Brown, Dogs Toys with Super Soft Fabric and Squeaker Inside, Machine Washable & Durable Dog Toys for Large Dogs to Small Dogs (5-30 kgs)…",
        price: 880,
        brand: "BarkButtler",
        ratings: "667",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ Squeaker Inside: Incorporated with a fun squeaker in the belly, these squeaky toys for dogs provide endless entertainment. The dog squeaky toy stimulates your dog's instincts by mimicking prey, keeping them engaged for hours.",
        description2: "✅ Super Durable Construction: These soft toys for dogs are strong dog toys, designed to withstand the toughest play with layers of reinforced fabric and tough stitching. This dog plush toy has added layers of fabric to withstand the test of time.",
    },

    {
        _id: "azaaa",
        image: [product63],
        name: "Dog Treats",
        fname: "Pedigree Biscrok Biscuits Dog Treats (Above 4 Months), Chicken Flavor, 900g Pack",
        price: 290,
        brand: "Pedigree",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: true,
        bestseller: false,
        sizes: ["500gm", "900gm"],
        description1: "✅ Delightfully crunchy dog treats for your pet. Bone shaped biscuits ideal to reward your during training or as festive treat for dogs With the goodness of protein and a source of calcium Fortified vitamins, minerals and omega fatty acids for overall health of pet.",
        description2: "✅ treat recommended for all dog breeds & life stages over 4 months of age. Each biscuit provides 15% Crude Protein, 7% Crude Fat & 5% Crude Fibre form_factor:dry material_features:non-vegetarian",
},

    {
        _id: "aabaa",
        image: [product39],
        name: "Electric Scissor",
        fname:"Pets Empire Grinder Clipper Nail Toe Trimmer Pet Dog Electric Grooming Scissors Tool Care by petpedicure",
        price: 298,
        brand: "Petpedicure",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ It's the newest and fastest way to keep your pet’s nails trim rounded and smooth with no mess. This product work quietly, it won't scare your pets. This item is the revolutionary nail trimmer for your dog.",
        description2: "✅ Now you can painlessly and easily trim your pet’s nails anywhere without the pain caused by traditional nail clippers. With On/Off switch, easy to use, Powered by 2 x AA batteries (Not included)",
    },
    {
        _id: "aacaa",
        image: [product46],
        fname: "KOZI PET Ultra Soft Ethnic Desingner Polyster Filled Reversable Brown and Black Dual Color for Dog Beds (Export Quality) - Small",
        name: "Dog Bed",
        price: 999,
        brand: "",
        ratings: "543",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L"],
        description1: "✅ Built like a couch, with extra length for multiple dogs or dogs who like to stretch out. Superior Material Dog Bed.The Dog Bed Made Of High-Grade, Safety-Certified Flannel Material with Soft PP Cotton Pad, Product Dimension 65 X 50 X 25,cm.",
        description2: "✅ Satisfied Warranty: We committed to providing an excellent experience for all customers. Type: Everyday Use Bed ,Suitable for all weathers, Easy to Carry.",
    },


    {
        _id: "aadaa",
        image: [product40],
        name: "Hair Dryer Brush",
        fname:"Magnova Store Dog Hair Dryer Brush for Dog | Portable 2 in 1 Pet Hair Dryer with Self Cleaning Slicker Brush, Dog Grooming Dryer & Comb, Professional Pet Blow Dryer Adjustable Temperature",
        price: 645,
        brand: "",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: " ✅ INNOVATIVE DOG DRYER & BRUSH IN ONE: This multi-functional 2-in-1 cat & dog hair dryer is the solution to dry your pet with loving care. After a bath, rainy walk, or on a cold winter’s day, this dog blow dryer and brush can be used to provide warmth and comfort to your dog or cat. In one smooth motion, you can brush and dry your pet. Simply push the hair removal button to remove shed hair within seconds!.",
        description2: "✅ PET-FRIENDLY DESIGN: The silent motor of this quiet pet blow dryer produces less then 70dB of noise, which will not scare your pet away. The slicker brush is comprised of stainless steel soft pins, featuring a protected tip with a slight angle – allowing you to reach deeply to your pet’s undercoat without scratching the skin",
    },

    {
        _id: "aaeaa",
        image: [product3],
        fname: "Pedigree 100% Vegetarian Dry Dog Food, Complete & Balanced Food For Adult Dogs, 3kg Pack",
        name: "Pedigree for Adult",
        price: 1207,
        brand: "Pedigree",
        ratings: "16k",
        category: "Food",
        subCategory: "Adultfood",
        featuredproduct: false,
        bestseller: false,
        sizes: ["1kg", "3kg", "5kg"],
        description1: "✅ Why feed them boring food when you can make every meal a feast with Pedigree? Pedigree introduces 100% vegetarian food for puppy and adult dogs that not only tastes scrumptious but also offers 5 signs of good health. With recipes based on research from the Waltham Centre for Pet Nutrition.",
        description2: "✅ Pedigree assures 5 signs of good health - healthy skin & coat, strong bones & teeth, healthy digestive system, strong muscles & stronger immune system. With the goodness of high-quality ingredients, this complete and balanced veg dog food offers a pawfect meal to pets, enticing their taste buds with a burst of delicious flavours.",
    },

    {
        _id: "aafaa",
        image: [product47],
        fname: "Qpets® Pet Use Breathable Reusable Female Dogs Diapers with 3 Absorbption Cotton Pad Comfort Reusable Doggy Diapers for Female Dog, Puppy(XL, Recommended Waist 16''-21'')",
        name: "Female Dogs Diapers",
        price: 458,
        brand: "",
        ratings: "45",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L", "XL"],
        description1: "✅ BREATHABLE MESH FABRIC: The washable puppy diapers for female small is made of comfortable double-layer polyester fabric of softness and comforness, lining mesh layer keeps good breathability for dog, suitable for all season use.",
        description2: "✅ ELASTIC WAIST AND QUICK RELEASE BUCKLE DESIGN: Elastic waist design can well fit the physical construction curves, prevents leakage. Recommended waist 16''-21'', suitable for Cocker spaniel, French Bulldog, Shepherd, Golden Retriever, etc",
    },

    {
        _id: "aagaa",
        image: [product41],
        name: "Hair Bath Brush",
        fname:"ZOIVANE Dog Brush for Hair, Dog Accessories, Dog Hair Brush, Dog Bathing Brush, Pet Brush, Dog Brush for Labrador, German Shepherd, Golden Retriever - Any Color (Pack of 1)",
        price: 210,
        brand: "",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ Material - Silicone. Usage/Application - For Bath. Size - Standard. Easy to use Silicon Dog Bath Brush Shampoo Dispenser. Packaging Ty",
    },

    {
        _id: "aahaa",
        image: [product53],
        name: "Dog Rope Toy",
        fname: "Foodie Puppies Cotton Dog Rope Toy for Aggressive Chewers, Tough Tug of War Large Dog Toys with Knots, Durable Cotton Rope Dog Chew Toy for Medium and Big Dogs- Washable (5 Knots Rope)",
        price: 240,
        brand: "",
        ratings: "667",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ SUPER SAFE NON-TOXIC Our Rope Dog Chew Toys are handmade by twining high quality cotton & polyester threads; this rope is further knotted together for added strength, protection & durability.",
    },

    {
        _id: "aaiaa",
        image: [product42],
        name: "Dog Trimmer for Paw",
        fname:"HASTHIP® Professional Dog Trimmer for Paw, Dog Hair Trimmers 2-Speed Dog Grooming Kit, Trimmer for Dogs Low Noise and Rechargeable Electric Hair Trimming",
        price: 1164,
        brand: "",
        ratings: "100",
        category: "Grooming",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ SAFE CERAMIC BLADE: This dog paw hair trimmer is D shaped cutter, will not hurt your pet's skin and won't get hot in use. The pet trimmer for dogs made of stainless steel, won't rust easily and more durable.",
        description2: "✅ 2 SPEED SWITCH & LOW NOISE: The cat hair trimmer features an adjustable, low high speed design. Faster and more effective, let your dog have a relax and enjoyable beauty experience. And pet clippers use the latest motor, high speed and less vibration. Its noise is less than 45 DB. Your pet will feel enjoyable and won't get nervous.",
    },

    {
        _id: "aajaa",
        image: [product59],
        name: "Shampoo Plus Conditioner for Dogs ",
        fname: "PAPA PAWSOME Itch No More Shampoo Plus Conditioner,for Dogs Clean Coat,Fresh Coat,Conditions Enriched with Tea Tree Oil|Lemongrass Oil|Neem Extract|Aloevera Extract, 250 ML",
        price: 365,
        brand: "Papa Pawsome",
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["100ml", "250ml"],
        description1: "✅ Shine O' Fur Shampoo: Nourishes the fur and reduces shedding. Improves coat shine and softness. A lovely lathery bath with shine o fur shampoo, and you don't need to worry anymore! Itch No More Shampoo: This body wash shampoo is a perfect natural option to care for your pet when it comes to bathe them or clean their coat and skin.",
        description2: "✅ Our all-natural body wash provide the best possible cleaning results and cleaning sensation to your pet. Nourishes fur, improves fur shine and softness, reduces shedding. Shine O' Pup: Soap-free with no harmful irritants or preservatives: leaves your pet's coat beautifully scented.",
    },

    {
        _id: "aakaa",
        image: [product66],
        name: "Dog Treats",
        fname: "Foodie Puppies Superbone All Natural Chicken Knotted Dog Treat, 7 in 1 (BBQ) | Highly-Digestible Training Chew Treat | Healthy and Tasty Snack Suitable for All Breeds of Dogs",
        price: 349,
        brand: "Superbone",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: true,
        bestseller: false,
        sizes: ["100gm", "250gm"],
        description1: "✅ Premium Quality Ingredients: Our chicken knotted bones are made from 100% all-natural, high-quality chicken breast, free from artificial additives, preservatives, or fillers. We prioritize your dog's health and ensure a wholesome treat they'll love.",
        description2: "✅ Ideal Training Aid: These knotted bones are perfectly sized and chewy, making them an excellent training reward. Reinforce positive behaviours or teach new tricks with these enticing treats. Promotes Dental Health: The natural chewing action of these treats helps reduce tartar and plaque build-up, contributing to better oral health for your furry companion.",
    },

    {
        _id: "aalaa",
        image: [product52],
        name: "Nylon Bone toy",
        fname: "Foodie Puppies Interactive Non-Toxic Nylon Arched Bone for Dogs and Puppies (Medium) | Durable Chewing, Teething, and Training Toy | Reduce Separation Anxiety",
        price: 190,
        brand: "",
        ratings: "667",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ BREATH - Help to remove the plaque and tartar, reduce the breeding of bacteria and freshen the breath. TEETHING - Help to keep teeth clean and massages gums, especially suitable for puppy dogs who love grinding their teeth.",
        description2: "✅ FRIENDLY - Safe and environmentally friendly Nylon Bone, durable and resistant to bite. INTERACTIVE - Perfect for interactive activities. Provides Long-Lasting Entertainment for powerful chewers and Fights Boredom.",
    },

    {
        _id: "aamaa",
        image: [product48],
        fname: "Bedsure Polyester Large Elevated Outdoor Dog Bed - Raised Dog Cots Beds for Large Dogs, Portable Indoor & Outdoor Pet Hammock Bed with Skid-Resistant Feet, Frame with Breathable Mesh, Grey (L)",
        name: "Dog Bed",
        brand: "",
        price: 2279,
        ratings: "543",
        category: "Accessories",
        subCategory: "",
        featuredproduct: false,
        bestseller: true,
        sizes: ["S", "L"],
        description1: "✅ Cooling Comfort: This dog bed's elevated design increases airflow for all season comfort, keeping your pet cool even on hot days. The height is just right for dogs of all ages, from puppies to seniors.", 
        description2: "✅ Indoor & Outdoor Use: Weather resistant, the 8' raised breathable mesh cot works great indoors and outside. Keep your pup dry and comfortable in the backyard, on the patio or porch, next to the pool, or while camping.",
    },
    

    {
        _id: "aanaa",
        image: [product60],
        name: "Dog Supplement and Multivitamin ",
        fname: "Henlo Everyday Nutrition Topper | Dog Supplement and Multivitamin | Improved Skin & Coat, Joint Support, Heart, and Gut Health Human Grade Ingredients | All Life Stages | 100g",
        price: 609,
        brand: "",
        ratings: "56",
        category: "Supplies",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["50gm", "100gm"],
        description1: "✅ Henlo Dog Supplement and Nutrition Topper has high palatability which ensures even the fussiest eaters get optimum dog nutrition, which also makes it a great dog food topper. The product contains Glucosamine and Chondroitin which makes it a great joint supplement for dogs. Glucosamine and Chondroitin together work towards maintaining and improving the health and cushioning of joints making it an excellent dog joint supplement.",
        description2:  "✅ The product also contains all essential vitamins for dogs (containing vitamins A, B, C, D, E) making it an essential multivitamin for dogs. The Henlo Dog Supplement and Nutrition Topper is made with 100% human grade antibiotic free chicken and has no artificial preservatives",
    },

    {
        _id: "aaoaa",
        image: [product65],
        name: "Dog Treats",
        fname: "Bark Out Loud by Vivaldis - Dental Sticks Sugar Free Adult Dog Treats Controls Plaque Tartar & Odourfor Dog Oral Care Chicken Dog Treats 110 GMS",
        price: 249,
        brand: "Bark Out Loud",
        category: "Treats",
        subCategory: "",
        ratings: "88k",
        featuredproduct: true,
        bestseller: false,
        sizes: ["110gm", "200gm"],
        description1: "✅ These chicken dental sticks help maintain the dental health and hygiene of your pet and give it a much fresher breath than before. Furthermore, these yummy treats reduce the buildup of Tartar as well.",
    },

    {
        _id: "aapaa",
        image: [product54],
        name: "Ring Chew Toy",
        fname: "The Dogs Company Rubber Dental Puppy Teething Spike Ring Chew Toy, 6 inches, Colour May Vary",
        price: 195,
        brand: "",
        ratings: "667",
        category: "Toys",
        subCategory: "",
        featuredproduct: false,
        bestseller: false,
        sizes: ["S", "L"],
        description1: "✅ SUPER SAFE NON-TOXIC Our Rubber Dog Chew Toys are made of hard natural rubber making it 100% safe for your pets, SUPER DURABLE and LONG LASTING, These nearly indestructible dog toys will entertain your dog for hours unlike squeaky or plush toys that get destroyed in minutes.",
        description2:  "✅ DENTAL CLEANING The spikes or soft grooves on the surface helps in cleaning and massaging the gums hence controlling plaque and tartar build up, GREAT FUN AND ENTERTAINMENT Every dog loves to play with his human parent and have fun together and our rubber chew dog toys facilitate the same . ",
    },


  ];